### PR TITLE
Rename project

### PR DESCRIPTION
**Pull request by andredublin**
Rename project implementation for https://github.com/fsprojects/Forge/issues/64

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Can you please rebase it? I was merging other PRs and we have some conflicts now.

**Comment by andredublin** [comment]
Doh will do

**Comment by andredublin** [comment]
@Krzysztof-Cieslak I've rebased the code to be caught up with master

**Comment by Krzysztof-Cieslak** [comment]
Great, thanks!

**Pull request merged**
