### PR TITLE
add .net core sdk preview2 (.net core 1.0 rtm) templates

### PR DESCRIPTION
**Pull request by enricosada**
- console
- lib

### CODE REVIEW

**Comment by enricosada** [comment]
waiting for suave .net core :smile:

**Comment by enricosada** [comment]
@Krzysztof-Cieslak the build fail is not about this pr, it's because travis try to build it as ruby proj running rake.

Can you disable build in travis if `.travis.yml` doesnt exists?

image

**Comment by fuszenecker** [comment]
Nice template, thanks, Enrico :-)

**Comment by Krzysztof-Cieslak** [comment]
Sorry for ignoring this for so long.

Problem with those templates is that by default we assume templates will work with Paket and FAKE. I can't merge it before we come up with some way of specifying that those templates should not use Paket and FAKE by default. So it will still wait for a while :(

**Comment by enricosada** [comment]
@Krzysztof-Cieslak well, i think people can use `dotnet new --lang f#` so is not really a big issue anymore.
It's easier to just not support `project.json` templates in forge, and wait for next .net core sdk preview (with fsproj support afaik)

**Pull request closed without merging**
