### PR TITLE
Fix #42: add "file type" command and ":type" syntax for "file add"

### LINKED ISSUE #42: forge file: manage file item type
It would be useful to manage file item types (Compile, Content, EmbeddedResource, etc).

Minimal support would be a command like `forge file type compile Foo.fs` to modify the type of a file that is already in the project (and fail if it's not there).

It would also be nice to be able to set the item type directly on `forge file add`. Unfortunately Argu doesn't allow passing an optional argument to a named parameter, so we can't allow both `forge file add Foo.fs` and `forge file add compile Foo.fs`. So maybe instead the syntax for both `type` and `add` (for consistency) could be something like `Foo.fs:compile`, with the `:compile` part being optional for `add` with the current defaults.

### PR DESCRIPTION
**Pull request by Tarmil**

### CODE REVIEW

**Comment by cloudRoutine** [comment]
I think `type` is a bad name for this, `build-action` is more clear about functionality and consistent with VS and Xamarin

**Comment by Tarmil** [comment]
Fair enough. `build-action` is a bit long for an argument name but those who care about that will just use `-b` anyway, so let's go with it.

**Comment by cloudRoutine** [comment]
it'll probably be easier to do this on top of https://github.com/fsprojects/Forge/pull/43 once it's merged since the project structure is changing and the commands are being moved into a different project

**Comment by Krzysztof-Cieslak** [comment]
I'm thinking about changing `forge file add` into `forge new:file` with 3 possible arguments `--name/-a`, `--template/-t` (file templates are part of #39, but it will be remade) and `--build-action/-b`

**Comment by Krzysztof-Cieslak** [comment]
Will be implemented as part of #49

**Pull request closed without merging**
